---
# Cluster access
kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config', true) }}"
namespace: "virtual-machines"

# VM identity & sizing
vm_name: "centos9-vm-demo-1"
cpu_cores: 2
memory: "2Gi"
disk_size: "30Gi"

# Storage
storage_class: "lvms-vg1"      # e.g. 'lvms-vg1', 'ocs-storagecluster-ceph-rbd'; empty = default SC
volume_mode: ""        # "", "Filesystem", or "Block" (try "Filesystem" if imports fail)

# Image (CDI HTTP import)
image_url: "https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2"

# First boot access
ssh_public_key: ""     # e.g. "ssh-ed25519 AAAA... user@host"
initial_password: "changeme"
ssh_password_auth: true

# Start policy
run_strategy: "Always" # Always | RerunOnFailure | Halt

# Waits
dv_wait_retries: 60
dv_wait_delay: 20
vm_wait_retries: 30
vm_wait_delay: 10
