---
# Cluster access
kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config', true) }}"
namespace: "virtual-machines"

# API IP Override
ocp_api_dns_name: api.sn05.duncan-networks.com
ocp_api_ip: 10.0.0.106
ocp_api_tcp_timeout: 10
ocp_api_curl_timeout: 10
ocp_api_k8s_wait_timeout: 30

# VM identity & sizing
vm_name: "centos9-vm-demo-1"
cpu_cores: 2
memory: "2Gi"
disk_size: "30Gi"

# Storage
storage_class: "lvms-vg1"
volume_mode: ""

# Image
image_url: "https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2"

# First boot access
ssh_public_key: ""
initial_password: "changeme"
ssh_password_auth: true

# SSH NodePort exposure
ssh_expose_enabled: true
ssh_service_name: "{{ vm_name }}-ssh"
ssh_service_port: 22
ssh_target_port: 22

# Empty = OpenShift auto-assigns a free NodePort.
# Example manual value: 30022
ssh_node_port: ""

# Service selector used to match the KubeVirt virt-launcher pod.
ssh_service_selector:
  vm.kubevirt.io/name: "{{ vm_name }}"
  kubevirt.io: virt-launcher

# Alternate selector if needed:
# ssh_service_selector:
#   kubevirt.io/domain: "{{ vm_name }}"
#   kubevirt.io: virt-launcher

ssh_endpoint_wait_retries: 12
ssh_endpoint_wait_delay: 5

# Start policy
run_strategy: "Always"

# Waits
dv_wait_retries: 60
dv_wait_delay: 20
vm_wait_retries: 30
vm_wait_delay: 10